name: Build and Compile Go project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23']  # Go 版本
        os: 
          - { goos: 'linux', goarch: 'amd64', os-name: 'linux-amd64' }
          - { goos: 'linux', goarch: 'arm64', os-name: 'linux-arm64' }

    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ matrix.os.os-name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-${{ matrix.os.os-name }}

      - name: Install dependencies
        run: |
          go mod download

      - name: Build for ${{ matrix.os.os-name }}
        env:
          GOOS: ${{ matrix.os.goos }}
          GOARCH: ${{ matrix.os.goarch }}
        run: |
          go build -o output/${{ matrix.os.os-name }}/main main.go

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os.os-name }}-binary
          path: output/${{ matrix.os.os-name }}/
