name: Build and Compile Go project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23']
        platform: 
          - goos: linux
            goarch: amd64
            platform-name: linux-amd64
          - goos: linux
            goarch: arm64
            platform-name: linux-arm64

    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ matrix.platform-name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-${{ matrix.platform-name }}

      - name: Install dependencies
        run: |
          go mod download

      - name: Build for ${{ matrix.platform-name }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          # 构建时给二进制文件加上平台后缀
          go build -o output/${{ matrix.platform-name }}/main-${{ matrix.platform-name }} main.go

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform-name }}-binary  # 为每个平台生成独立的 artifact
          path: output/${{ matrix.platform-name }}/main-${{ matrix.platform-name }}  # 指定唯一的二进制文件名
