name: Build and Compile Go project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23']  # 使用和 go.mod 中一致的版本
        platform: 
          - { goos: 'linux', goarch: 'amd64', platform-name: 'linux-amd64' }
          - { goos: 'linux', goarch: 'arm64', platform-name: 'linux-arm64' }

    timeout-minutes: 30

    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          # 缓存路径
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          # 缓存键，确保唯一性
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ matrix.platform-name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-${{ matrix.platform-name }}

      - name: Install dependencies
        run: |
          go mod download

      - name: Build for ${{ matrix.platform-name }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -o output/${{ matrix.platform-name }}/main main.go

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform-name }}-binary  # 使用合法的名称
          path: output/${{ matrix.platform-name }}/
