name: Dev Build and Pre-Release

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23']
        os: 
          - { goos: 'linux', goarch: 'amd64', os-name: 'linux-amd64' }
          - { goos: 'linux', goarch: 'arm64', os-name: 'linux-arm64' }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Go
        uses: actions/setup-go@v5  # Updated to v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go mod download

      - name: Build for ${{ matrix.os.os-name }}
        env:
          GOOS: ${{ matrix.os.goos }}
          GOARCH: ${{ matrix.os.goarch }}
        run: |
          go build -o output/YASS-${{ matrix.os.os-name }}/YASS-${{ matrix.os.os-name }} main.go

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: ${{ matrix.os.os-name }}-binary
          path: output/YASS-${{ matrix.os.os-name }}/YASS-${{ matrix.os.os-name }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Delete previous pre-release
        run: |
          PREV_TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          if [ -n "$PREV_TAG" ]; then
            gh release delete "$PREV_TAG" --yes
          else
            echo "No previous release found."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set release version
        id: version
        run: |
          SHORT_SHA=$(git rev-parse --short=7 ${{ github.sha }})
          VERSION="dev-$SHORT_SHA"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download artifacts
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          path: ./artifacts

      - name: Create GitHub Pre-Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: "Pre-Release ${{ env.VERSION }}"
          body: |
            预发布版本:
            - Branch: ${{ github.ref }}
            - Commit: ${{ github.sha }}
          draft: false
          prerelease: true

      - name: Upload Linux-amd64 binary to Pre-Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/linux-amd64-binary/YASS-linux-amd64
          asset_name: YASS-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Linux-arm64 binary to Pre-Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/linux-arm64-binary/YASS-linux-arm64
          asset_name: YASS-linux-arm64
          asset_content_type: application/octet-stream
